/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Coche;
import Modelo.Peaton;
import Modelo.SemaforoH;
import java.awt.Color;
import java.util.concurrent.Semaphore;

/**
 *
 * @author santi
 */
public class Semaforo extends javax.swing.JFrame {

    Coche c;
    Peaton p;
    SemaforoH s;
    Semaphore semaf = new Semaphore(0, true);

    /**
     * Creates new form Semaforo
     */
    public Semaforo() {
        
        initComponents();
        
        c = new Coche(carro2, limiteCarro.getX(), semaf);
        p = new Peaton("Laura", persona1, limitePersona.getY(), semaf);
        s = new SemaforoH(rojo, amarillo, verde, semaf);
        
        this.setSize(600, 500);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Semaforo");
        this.verde.setBackground(Color.gray);
        this.amarillo.setBackground(Color.gray);
        this.rojo.setBackground(Color.gray);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        carro2 = new javax.swing.JLabel();
        persona1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        amarillo = new javax.swing.JButton();
        rojo = new javax.swing.JButton();
        verde = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        limitePersona = new javax.swing.JLabel();
        limiteCarro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        carro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/da82fedda59c1e00f5c146ade0a2e4c4-silueta-compacta-de-la-vista-lateral-del-coche-by-vexels.png"))); // NOI18N
        getContentPane().add(carro2);
        carro2.setBounds(70, 170, 100, 54);

        persona1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/6aa09e0e57a41b377d066e26f22519ab-icono-de-transporte-de-usuario-de-la-persona-by-vexels.png"))); // NOI18N
        getContentPane().add(persona1);
        persona1.setBounds(250, 360, 90, 100);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/paso-peatonal-png-4.png"))); // NOI18N
        jLabel2.setText("\\");
            getContentPane().add(jLabel2);
            jLabel2.setBounds(270, 30, 60, 100);

            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/paso-peatonal-png-4.png"))); // NOI18N
            jLabel3.setText("\\");
                getContentPane().add(jLabel3);
                jLabel3.setBounds(270, 220, 60, 100);
                getContentPane().add(amarillo);
                amarillo.setBounds(120, 40, 30, 30);
                getContentPane().add(rojo);
                rojo.setBounds(120, 10, 30, 30);
                getContentPane().add(verde);
                verde.setBounds(120, 70, 30, 30);

                jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/semaforo-png-3.png"))); // NOI18N
                getContentPane().add(jLabel4);
                jLabel4.setBounds(85, 0, 89, 112);

                jButton4.setText("Empezar Semaforo");
                jButton4.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton4ActionPerformed(evt);
                    }
                });
                getContentPane().add(jButton4);
                jButton4.setBounds(70, 400, 140, 25);

                jButton5.setText("Detener Semaforo");
                jButton5.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton5ActionPerformed(evt);
                    }
                });
                getContentPane().add(jButton5);
                jButton5.setBounds(70, 440, 140, 25);

                jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/paso-peatonal-png-4.png"))); // NOI18N
                jLabel6.setText("\\");
                    getContentPane().add(jLabel6);
                    jLabel6.setBounds(270, 130, 60, 100);
                    getContentPane().add(limitePersona);
                    limitePersona.setBounds(370, 10, 30, 20);
                    getContentPane().add(limiteCarro);
                    limiteCarro.setBounds(470, 110, 30, 30);

                    pack();
                }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        s.start();
        p.start();
        c.start();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        c.stop();
        p.stop();
        c.stop();
        s.stop();
        
        c.dejarAlInicio();
        p.dejarAlInicio();
        c = new Coche(carro2, limiteCarro.getX(), semaf);
        p = new Peaton("Laura", persona1, limitePersona.getY(), semaf);
        s = new SemaforoH(rojo, amarillo, verde, semaf);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Semaforo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Semaforo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Semaforo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Semaforo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Semaforo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton amarillo;
    private javax.swing.JLabel carro2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel limiteCarro;
    private javax.swing.JLabel limitePersona;
    private javax.swing.JLabel persona1;
    private javax.swing.JButton rojo;
    private javax.swing.JButton verde;
    // End of variables declaration//GEN-END:variables
}
